[package]
name = "reboot-arch-btw"
version = "0.2.0"
repository = "https://github.com/rnestler/reboot-arch-btw"
license = "GPL-3.0-only"
authors = [
  "Raphael Nestler <raphael.nestler@gmail.com>",
  "Stefan Schindler <stefan@estada.ch>",
  "Danilo Bargen <mail@dbrgn.ch>",
]
description = "Check if you need to reboot due to an updated kernel. (I use Arch btw!)"
readme = "README.md"
keywords = ["i-use-arch-btw", "arch", "linux", "kernel"]
categories = ["command-line-utilities"]
include = [
    "**/*.rs",
    "Cargo.toml",
    "Cargo.lock",
    "README.md",
]
edition = "2018"

[dependencies]
alpm = "0.9"
docopt = "1.1"
notify-rust = "3.0"
serde = "1.0"
serde_derive = "1.0"
