name: CI
on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-20.04
    container: rnestler/archlinux-rust:1.53.0
    steps:
      - uses: actions/checkout@v2
      - name: Move .rustup to new $HOME
        run: mv /root/.rustup $HOME/
      - run: cargo build
      - run: cargo test

  lint:
    runs-on: ubuntu-20.04
    container: rnestler/archlinux-rust:1.53.0
    steps:
      - uses: actions/checkout@v2
      - name: Move .rustup to new $HOME
        run: mv /root/.rustup $HOME/
      - run: rustup component add clippy
      - run: cargo clippy --all-targets --all-features -- -D warnings

  fmt:
    runs-on: ubuntu-20.04
    container: rnestler/archlinux-rust:1.53.0
    steps:
      - uses: actions/checkout@v2
      - name: Move .rustup to new $HOME
        run: mv /root/.rustup $HOME/
      - run: rustup component add rustfmt
      - run: cargo fmt -- --check

  audit:
    runs-on: ubuntu-20.04
    container: rnestler/archlinux-rust:1.53.0
    steps:
      - uses: actions/checkout@v2
      - name: Move .rustup to new $HOME
        run: mv /root/.rustup $HOME/
      - run: pacman --noconfirm -Sy cargo-audit
      - run: cargo audit
